import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/NavBar";
import localFont from "next/font/local";
import Footer from "@/components/Footer";
import MobileNav from "@/components/MobileNav";

const chillax = localFont({
  src: "../../../public/fonts/Chillax-Variable.ttf",
  variable: "--font-chillax",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-poppins",

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${chillax.variable}`}>
        <Navbar className="hidden md:block"/>
        <MobileNav/>
          {children}
          <Footer/>
      </body>
    </html>
  );
}
